Extend the role to allow linking to entire repos
astrojuanlu/sphinx-github-role pull request #19
Opened 2022-02-14 02:43 UTC by zml2008

Fixes #17

This implements the change I described in #17.

There was one required change to an existing test, since what was previously a malformed link now could now be a reference to a GitHub repository. This has produced a different failure message.

I've not spent a ton of time working with Python projects before, so let me know if there's anything you'd like changed.

2022-02-16 22:15 UTC, astrojuanlu requested changes
Thanks a lot for your pull request @zml2008! It looks quite good, added a few comments.

2022-02-16 22:15 UTC, astrojuanlu commented on src/sphinx_github_role/__init__.py
> +            print(self.target)
```suggestion
```

Leftover from debugging?

2022-02-16 22:15 UTC, astrojuanlu commented on src/sphinx_github_role/__init__.py
> +            )
What about this?

```suggestion
        if proj_only:
            refuri = self.gh_tpl.format(**parts)
        else:
            refuri = self.gh_issue_tpl.format(**parts)
        node = nodes.reference(
            self.rawtext,
            self.title,
            refuri=refuri,
        )
```

2022-02-18 03:03 UTC, zml2008 commented
Thanks! that was a leftover you caught :)

I've applied your suggestions with minor formatting changes to make `black` happy.

2022-02-18 05:48 UTC, astrojuanlu approved these changes
This all looks great to me!

2022-02-18 05:49 UTC, merged